import Head from "next/head";
import axios from "axios";

export default function Home({ repo }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{JSON.stringify(repo)}</main>
    </>
  );
}

export const getServerSideProps = async ({ req, params, res }) => {
  const _res = await fetch("https://api.github.com/repos/vercel/next.js");
  const repo = await _res.json();
  return { props: { repo } };
};
