import Head from "next/head";

export default function Whatever({ someProp }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{someProp}</main>
    </>
  );
}

export const getServerSideProps = async ({ req, params, res }) => {
  return {
    props: {
      someProp: "Hello World",
    },
  };
};
